# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ftbot.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66tbot.proto\x12\x05\x66tbot\"3\n\x10SetSpeedSteering\x12\r\n\x05speed\x18\x01 \x01(\x02\x12\x10\n\x08steering\x18\x02 \x01(\x02\"Q\n\x0bRobotStatus\x12\x17\n\x0ftrue_left_speed\x18\x01 \x01(\x02\x12\x18\n\x10true_right_speed\x18\x02 \x01(\x02\x12\x0f\n\x07voltage\x18\x03 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ftbot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETSPEEDSTEERING']._serialized_start=22
  _globals['_SETSPEEDSTEERING']._serialized_end=73
  _globals['_ROBOTSTATUS']._serialized_start=75
  _globals['_ROBOTSTATUS']._serialized_end=156
# @@protoc_insertion_point(module_scope)
