/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "ftbot.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ftbot_SetSpeedSteering, ftbot_SetSpeedSteering, AUTO)


PB_BIND(ftbot_RobotStatus, ftbot_RobotStatus, AUTO)



